set(EGALITO_BUILD_DIR ${CMAKE_CURRENT_LIST_DIR}/build)
set(EGALITO_BINARY_DIR ${EGALITO_BUILD_DIR}/bin)
set(EGALITO_LIBRARY_DIR ${EGALITO_BUILD_DIR}/lib)
set(EGALITO_STATIC_DIR ${EGALITO_BUILD_DIR}/static)
set(EGALITO_HEADER_DIR ${EGALITO_BUILD_DIR}/include/src)
set(EGALITO_PKGCFG_DIR ${EGALITO_BUILD_DIR}/pkgconfig)


execute_process(COMMAND lsb_release --short --codename
              OUTPUT_VARIABLE DEB_RELEASE
OUTPUT_STRIP_TRAILING_WHITESPACE)
set(LIBGTIRB_DEPENDS_SUFFIX " (=${CPACK_GTIRB_VERSION}-${DEB_RELEASE})")

if(CPACK_EGALITO_PACKAGE STREQUAL  "lib")
  #debian
  set(CPACK_INSTALLED_DIRECTORIES 
    ${EGALITO_LIBRARY_DIR} "usr/lib"
    "${EGALITO_DEP_DIR}/libegalito.so" "usr/lib/egalito"
    )
  set(CPACK_PACKAGE_NAME "libegalito")
  set(CPACK_DEBIAN_PACKAGE_DEPENDS 
    "libc6, libcapstone-dev, libgtirb${LIBGTIRB_DEPENDS_SUFFIX}"
  )
  #rpm: todo
elseif(CPACK_EGALITO_PACKAGE STREQUAL "dev")
  set(CPACK_INSTALLED_DIRECTORIES 
    ${EGALITO_HEADER_DIR} "usr/include/egalito"
    ${EGALITO_PKGCFG_DIR} "usr/lib/pkgconfig"
    )
  set(CPACK_PACKAGE_NAME "libegalito-dev")
  #TODO: GET CAPSTONE VERSION PROGRAMATICALLY
  set(CPACK_DEBIAN_PACKAGE_DEPENDS "libegalito (=${CPACK_PACKAGE_VERSION}), libgtirb-dev${LIBGTIRB_DEPENDS_SUFFIX}") 
elseif(CPACK_EGALITO_PACKAGE STREQUAL "bin") 
  set(CPACK_INSTALLED_DIRECTORIES ${EGALITO_BINARY_DIR} "usr/bin")
  set(CPACK_PACKAGE_NAME "egalito")
  #debian
  set(CPACK_DEBIAN_PACKAGE_DEPENDS "libegalito")
  #rpm: todo
elseif(CPACK_EGALITO_PACKAGE STREQUAL "static")
  set(CPACK_INSTALLED_DIRECTORIES ${EGALITO_STATIC_DIR} "usr/lib")
  set(CPACK_PACKAGE_NAME "libegalito-static")
else()
  message("Unknown value for CPACK_EGALITO_PACKAGE")
  return()
endif()

set(CPACK_DEBIAN_PACKAGE_NAME ${CPACK_PACKAGE_NAME})
set(CPACK_RPM_PACKAGE_NAME ${CPACK_PACKAGE_NAME})
set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION})
