# The base OS of the docker image can be modified by providing (e.g.)
# --build-arg BASE_IMAGE=ubuntu:18.04
# to docker build
ARG BASE_IMAGE="debian:bullseye"

# Build a docker image with the dependencies for building and installing egalito
FROM ${BASE_IMAGE} AS dependencies

# Record installed version of libstdc++6 and install matching dbg package.
RUN STDCPP_VERSION=$(dpkg -s libstdc++6 | grep -oP 'Version: \K\d+') && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
  build-essential \
  g++ \
  gdb \
  git \
  gosu \
  libc6-dbg \
  libstdc++6-$STDCPP_VERSION-dbg \
  libreadline-dev \
  lsb-release \
  unzip

# Add debug repository and install debug symbols, if needed
RUN echo "Preparing debug symbols..." && \
    # If bookworm, a different approach is needed
    if [ "$(lsb_release -cs)" = "bookworm" ]; then \
        echo "deb http://deb.debian.org/debian-debug $(lsb_release -cs)-debug main" > /etc/apt/sources.list.d/debian-debug.list && \
        apt-get update && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y libstdc++6-dbgsym; \
    else \
        DEBIAN_FRONTEND=noninteractive apt-get install -y libstdc++6-7-dbg; \
    fi

FROM dependencies AS test

# TODO - use pre-commit package for Debian
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install -y python3-pip lcov && \
    python3 -m pip install pre-commit


CMD ["/bin/bash"]

# Add the script which allows you to run the docker image as a specific user
# for easier development work when volumes are mounted
FROM test AS dev
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

