FROM ubuntu:18.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
build-essential \
clang-format-6.0 \
lsb-release \
gdb \
g++ \
git \
gosu \
lcov \
libc6-dbg \
libstdc++6-7-dbg \
libcapstone-dev \
libreadline-dev \
libboost-python-dev \
python3 python3-pip \
unzip \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN  python3 -m pip install --upgrade pip && \
     python3 -m pip install pre-commit 

RUN ln -s  /usr/bin/clang-format-6.0 /usr/bin/clang-format



CMD ["/bin/bash"]
